---
# Talk to all hosts just so we can learn about them (gather fatcs)
# and create dynamic groups as needed to slice the environment.
- hosts: all
  tasks:
   - name: Group nodes by ansible_system (Linux, FreeBSD, Win32NT)
     group_by: key={{ ansible_system }}

   - name: Group nodes by ansible_os_family (Debian, RedHat, Suse etc)
     group_by: key={{ ansible_os_family }}

   - name: Group nodes by ansible_distribution (Ubuntu, CentOS, Fedora etc)
     group_by: key={{ ansible_distribution }}

   - name: Group nodes by ansible_distribution and ansible_distribution_major_version (Well guess :)
     group_by: key="{{ ansible_distribution }}-{{ ansible_distribution_major_version }}"


- hosts: loc-dev
  gather_facts: False
  roles:
   - apache-maven
   - go
